### ISSUE TITLE
One Python interpreter per example

### ISSUE THREAD

**Issue by jeertmans** [byexamples/byexample#276]
Hello @eldipa, is it somewhat possible to have different interpreter per file?

Even though this may not run fast, I somewhat would like to run each example in my docstrings with separate interpreters.

This is especially useful because I use Just In Time (jit) compilation, and I want to test different compilations mechanisms, which is not possible with one interpreter for a whole file.

**Comment by eldipa** [comment]
Hi @jeertmans , no, `byexample` does not support to run the same file under different interpreters of the same language but may be it is not necessary.

Would calling [jax.clear_caches](https://github.com/google/jax/discussions/10826#discussioncomment-5572258) after each example enough?  May be this [ugly hack](https://github.com/google/jax/issues/10828#issuecomment-1138428231)?

Note: I never used `jax` so I may be saying nonsense! Let me know what do you think or if you can provide an example of how you would like to see it.

**Comment by jeertmans** [comment]
Thanks for the reply @eldipa! Yes, I was aware of the `clear_cache` function, but the problem is that it would like to "hide" this function calls in my docs.

But it seems like this is not possible, see discussion here: https://discuss.python.org/t/a-standard-for-non-displaying-executable-lines-of-code-in-documentation/16570.

However, this is not a problem caused by `byexample` here :-)
