### ISSUE TITLE
Docker example

### ISSUE THREAD

**Issue by rmharrison** [byexamples/byexample#60]
Since I use docker and docker-compose extensively in my README.md's, I took a stab at using byexample...

```shell
# What I really want to show in the README
$ docker run -d -p 27017:27017 mongo:3.4.2
<dockerId>
```

```shell
# Testing that the command works + teardown
$ docker ps --no-trunc -q | grep -c <dockerId> # byexample: +paste
1

$ docker rm -f <dockerId> # byexample: +paste -tags
<dockerId>

$ docker ps --no-trunc -q | grep -c <dockerId> # byexample: +paste
0
```

Thoughts?

**Comment by eldipa** [comment]
Some random thoughts:
 - You may want to extend the timeout of the ``docker run`` with ``+timeout`` or other number, at least in my machine docker is a little slow.
 - For the ``docker run`` and the first ``docker ps`` I would add ``+fail-fast``: if the count of containers is not 1, this example will fail and it will skip the rest of the examples in your readme. (I'm assuming that you are running more examples below that depend on a that container.)
 - You may want to add a little sleep between the run and the first ``docker ps``: I found that a container may start but die after. Of course, this will depend of what kind of container are you running. 
 - You should add ``-skip`` to the ``docker rm`` to make sure that the example is executed even if another example fails (but see my comments below)
 - The last ``docker ps`` could be removed: in theory, if the ``docker rm`` fails it should print something different than ``<dockerId>`` and that is enough to know that something went wrong.

This is my README.md:

```shell
$ docker run -d -p 27017:27017 mongo:3.4.2     # byexample: +timeout=10 +fail-fast
<dockerId>

$ sleep 5 && docker ps --no-trunc -q | grep -c <dockerId>    # byexample: +paste +timeout=10 +fail-fast
1

# ...more examples here....

$ docker rm -f <dockerId>                      # byexample: +paste -tags -skip
<dockerId>
```

##### Notes about teardown:

The option ``-skip`` will force the execution of the example but this is not bullet proof.

If one example time out, ``byexample`` assumes that the interpreter that ran the example is in an undefined state and so it can execute any another example even if it has ``-skip``. It is possible to workaround this in some cases (``byexample`` could spawn another shell and run there the example.... but it is not easy and it is not a general solution)

In my experience this is not a real issue in practice and it doesn't worth the effort, but I can be wrong.
