### ISSUE TITLE
Dockerfile PR?

### ISSUE THREAD

**Issue by rmharrison** [byexamples/byexample#61]
Would you accept a PR for a Dockerfile? 

Requires that execution with `$ byexample` is resolved, see: https://github.com/byexamples/byexample/issues/59

---
Note to self:
- Use `ENTRYPOINT` instead of `CMD` in Dockerfile, see: https://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile

**Comment by eldipa** [comment]
Well, I would need to see the PR first ;) 

I don't know how useful would be a Dockerfile: the container would have ``byexample`` installed by default (I guess) but in the practice an user may want to install other stuffs as well. He may have a Dockerfile with those already.

But I may just missing the point, so go ahead with the PR, what is the worst thing that could happen?
