### ISSUE TITLE
License not packaged on PyPI

### ISSUE THREAD

**Issue by saraedum** [byexamples/byexample#89]
The license file is not distributed in the tarball on PyPI. Would you mind including it with the next release?

See https://github.com/conda-forge/staged-recipes/pull/8997

**Comment by saraedum** [comment]
Btw., the files do not seem to have copyright headers, so I am wondering: Is this licensed under GPL3 or "GPL3 or at your option any later version"?

**Comment by eldipa** [comment]
Hi @saraedum, thanks for taking some time to review this!, The license should be packaged with the rest of the code so if doesn't, it is definitely a bug. I will check the scripts that I have that bundle this, I hope to have a fix for today.

About the copyright headers, yes, all the code is licensed under GLP3. I'm not a lawyer but I think that it is enough to put a single LICENSE file in the root of the project and the copyright header was not necessary.

Let me know if `conda` has a requirement about this. 

And thanks again!

**Comment by saraedum** [comment]
You are right, you don't need to include a header with each file. However, the LICENSE file in your repository actually says:
```
            How to Apply These Terms to Your New Programs

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.
[...]
```

The advantage to putting this into every source file is that people can copy files into their projects and the license & copyright comes with the file automatically. Another advantage is that it makes it clear explicitly whether you licensing under "GPLv3 only" or "GPLv3 or a later version of the GPL license."

In any case, I agree that it's not necessary, it is to a large extent a matter of taste.

**Comment by saraedum** [comment]
conda has no requirement about this btw.
