### ISSUE TITLE
On Windows, use a equivalent POSIX version of fcntl

### ISSUE THREAD

**Issue by saraedum** [byexamples/byexample#90]
Is it intentional that this does not work on Windows?

https://github.com/conda-forge/staged-recipes/pull/8997#issuecomment-517307267

**Comment by eldipa** [comment]
Yes and no. `fcntl` is used to protect a file from a race condition using file locks. It is implemented in linux but it is perfectly possible to use something similar in Windows (I will need to do some research about this).

But the fundamental problem is not in `fcntl` but in `pexpect`. `byexample` runs *interactive* interpreters and most of them behave very different if they are running from a terminal (*interactive*) or from a file/pipe.
`pexpect` runs the interpreters using a terminal but the concept of "terminal" is also linux specific. In Windows `pexpect` falls back to a pipe so the interpreter *may* detect this as *non-interactive* so `byexample` will not run correctly on that platform.

Of course this depends of the interpreter (Python, Ruby, ...). Honestly I didn't run any experiment in a Windows environment so I'm not sure what would be the results.

Anyway, I'm going to look for a Windows equivalent `fcntl`

**Comment by eldipa** [comment]
If you don't mind, I will change the title of the issue to reflect this, something like "On Windows, use a equivalent POSIX version of `fcntl`"

**Comment by eldipa** [comment]
Just for references:
 - https://github.com/benediktschmitt/py-filelock

**Comment by saraedum** [comment]
Yes, please go ahead and change the title. And you are right, pexpect under Windows can be very tricky. (as a SageMath developer I've had my pexpect battles…)
